POST https://testando-o-node.onrender.com/videos
Content-Type: application/json

{
    "title": "Como usar o node",
    "description": "esse é o primeiro video",
    "duration": 180
}

###

GET https://testando-o-node.onrender.com/videos

###

PUT https://testando-o-node.onrender.com/videos/8a7c6d92-3285-4baa-99f9-bbcb67e90c19
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Comclui o teste de Node",
    "duration": 180
}

###

DELETE https://testando-o-node.onrender.com/videos/8a7c6d92-3285-4baa-99f9-bbcb67e90c19